#!/bin/bash

apt update
apt upgrade -y

# Install System Commands

apt install -y \
    htop \
    mytop \
    net-tools \
    curl \
    unzip

# Install and Configure Nginx

apt install -y nginx
sed -i 's/root \/var\/www\/html;/root \/var\/www\/public;/' /etc/nginx/sites-available/default
sed -i '/# pass PHP scripts to FastCGI server/,/#}/c\\tlocation ~ \\.php$ {\n\t\tinclude snippets/fastcgi-php.conf;\n\t\tfastcgi_pass unix:/run/php/php7.4-fpm.sock;\n\t}' /etc/nginx/sites-available/default
sed -i 's/index index.html/index index.php index.html/' /etc/nginx/sites-available/default

# Install PHP 7.4 and Extensions

apt install -y \
    php7.4 \
    php7.4-bcmath \
    php7.4-cli \
    php7.4-ctype \
    php7.4-curl \
    php7.4-fileinfo \
    php7.4-fpm \
    php7.4-gd \
    php7.4-igbinary \
    php7.4-imagick \
    php7.4-imap \
    php7.4-intl \
    php7.4-json \
    php7.4-ldap \
    php7.4-mbstring \
    php7.4-memcached \
    php7.4-msgpack \
    php7.4-mysql \
    php7.4-pcov \
    php7.4-pdo \
    php7.4-pgsql \
    php7.4-readline \
    php7.4-redis \
    php7.4-soap \
    php7.4-tokenizer \
    php7.4-xdebug \
    php7.4-xml \
    php7.4-zip

# Install Application Schedulers

apt install -y \
    cron \
    supervisor

# Install Composer 2.x

curl -sS https://getcomposer.org/installer -o composer-setup.php
php composer-setup.php --install-dir=/usr/local/bin --filename=composer

# Install Node 16.x

curl -sL https://deb.nodesource.com/setup_16.x | bash -
apt install -y nodejs
npm install -g npm
